### ISSUE TITLE
关于低光照图像增强的数据集

### ISSUE THREAD

**Issue by cjl506** [Fayeben/GenerativeDiffusionPrior#10]
作者是对低光照数据集如何处理的呢，需要.npy文件，请教一下 作者的数据集是resize了吗？？？，'/nvme/feiben/DDPM_Beat_GAN/scripts/imagenet_dataloader/LOL_low_resolution_256.npz

**Comment by Fayeben** [comment]
Hi, we do not resize the low light images. You can find these .npz files in this link: https://github.com/Fayeben/GenerativeDiffusionPrior/issues/1#issuecomment-1525588861

**Comment by cjl506** [comment]
Thank you for your attention to my question and reply. Good luck in scientific research!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fayeben/GenerativeDiffusionPrior"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月31日(星期三) 上午9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fayeben/GenerativeDiffusionPrior] 关于低光照图像增强的数据集 (Issue #10)





 
Hi, we do not resize the low light images. You can find these .npz files in this link: #1 (comment)

**Comment by Fayeben** [comment]
Since we use the 256*256 pre-trained model for sampling, we need to leverage a patch-based method to recover the images. For a 600*400 image, there are 30 patches that need to be sampled. We have discussed the sampling speed in the limitation section.
As for the quality, we use the model pre-trained on ImageNet, therefore, there will be little difference from the GT, but they will be acceptable for humans. We run the script we provided again and list all the images below. Could you tell us which one does not meet your need or give us more suggestions to improve it?
![图片 1](https://github.com/Fayeben/GenerativeDiffusionPrior/assets/45416309/1c4d9898-c1a8-4da0-853f-bdfb364b78dc)
![图片 2](https://github.com/Fayeben/GenerativeDiffusionPrior/assets/45416309/6e749974-6d12-4ef5-9dcf-27095c5f3d53)
![图片 3](https://github.com/Fayeben/GenerativeDiffusionPrior/assets/45416309/012f1ad3-9340-47f1-80d9-25969a025048)
![图片 5](https://github.com/Fayeben/GenerativeDiffusionPrior/assets/45416309/fee2a612-1084-4302-ab9c-1f3c1fbe80f0)
![图片 4](https://github.com/Fayeben/GenerativeDiffusionPrior/assets/45416309/73c0c1cd-b846-45a0-afd0-8d8a1d20477e)

**Comment by cjl506** [comment]
不好意思，扩散模型是一种很新的方法，我没有否认你的工作没有创新。因为毕竟无监督算法复原任务很困难。就推理速度和还原质量来讲我觉得打不过现有的很多无监督方法。关于人们视觉满意程度，每个人都不一样。我觉得179.png效果比较好。毕竟这是个有lable 的数据集，当我在知道真实值的情况下，请允许我有这样的感受。作者能否和公开一下你的tarin.py  文件。我很想知道如果不是无监督，而是有监督的话，使用扩散先验能够达到多少呢？这样扩散模型能不能比较准确的把图像退化建模出来呢？谢谢你的关注与认真的回复，科研顺利！
