### ISSUE TITLE
Condition_mean function Imapementation and usage

### ISSUE THREAD

**Issue by opherbambi** [Fayeben/GenerativeDiffusionPrior#27]
Hi, 
Few questions about the "condition_mean" usage. in the file - "gaussian_diffusion_x0_enhancement_direct.py"

1. There is a loop over the "condition_mean" function, which runs it twice. 
 What is the reason for that?

2. The "condition_mean" function contains an optimizer for the p_mean_var["mean"] variable.
As much as I understand the process, the optimization of the mean happens with the gradient of the "cond_fn".
Why do you choose to use the optimizer?

3. In the ablation study, there is an explaination about GDP with and without Sigma.
Probably I am missing something. 
How or where it is expressed in the code?

Thanks

**Comment by Feynben** [comment]
Hello, since we are busy with our project, we are sorry for the late reply. 

1. We can add guidance in one denoising step in several times. And we will correspondly use a smaller guidance scale. It uses just like gradient descent.

2. Since we hope to add guidance in one denoising step in several times. We think using an optimizer might be helpful. But directly using loops can also obtain great results.

3.  We do not use Sigma, the related code is in https://github.com/Fayeben/GenerativeDiffusionPrior/blob/b34494cd53e344a5c726e502f552cd7fb888aad0/scripts/guided_diffusion/gaussian_diffusion.py#L368
