### ISSUE TITLE
colorization task not work well

### ISSUE THREAD

**Issue by chensming** [Fayeben/GenerativeDiffusionPrior#6]
Hi, bro, nice jobs! I am interested in it and I try I repeat the experiment. When I run these script:
`MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond False --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
python sample_x0_color.py  $MODEL_FLAGS --use_img_for_guidance --start_from_scratch --save_png_files`
It doesn't work in some pictures. could you help me about it?
In the pic, the first example seems work, but the orders didn't. (The pictures come from imagenet/val/n03781244)
![1683616000784](https://user-images.githubusercontent.com/45591767/237020339-3164c5c0-40c6-4227-9f01-132525739d60.jpg)

**Comment by Fayeben** [comment]
Thanks! Since colorization is not a trivial task, maybe you can try to modify the weight of loss and guidance scale to solve this problem.
https://github.com/Fayeben/GenerativeDiffusionPrior/blob/116b875db9b4b6c3bcc8adcfc7dbaedb607e1edb/scripts/sample_x0_color.py#L112
https://github.com/Fayeben/GenerativeDiffusionPrior/blob/116b875db9b4b6c3bcc8adcfc7dbaedb607e1edb/scripts/sample_x0_color.py#L252

**Comment by chensming** [comment]
> 
ok. I will give it a try, thanks!

**Comment by Fayeben** [comment]
Since there are no more questions, I'll mark it closed. If you still have some questions, please feel free to ask. Thanks!
